<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data\ReadStreamEventsCompleted;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.ReadStreamEventsCompleted.ReadStreamResult</code>
 */
class ReadStreamResult
{
    /**
     * Generated from protobuf enum <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * Generated from protobuf enum <code>NoStream = 1;</code>
     */
    const NoStream = 1;
    /**
     * Generated from protobuf enum <code>StreamDeleted = 2;</code>
     */
    const StreamDeleted = 2;
    /**
     * Generated from protobuf enum <code>NotModified = 3;</code>
     */
    const NotModified = 3;
    /**
     * Generated from protobuf enum <code>Error = 4;</code>
     */
    const Error = 4;
    /**
     * Generated from protobuf enum <code>AccessDenied = 5;</code>
     */
    const AccessDenied = 5;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ReadStreamResult::class, \Rxnet\EventStore\Data\ReadStreamEventsCompleted_ReadStreamResult::class);

