<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data\SubscriptionDropped;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.SubscriptionDropped.SubscriptionDropReason</code>
 */
class SubscriptionDropReason
{
    /**
     * Generated from protobuf enum <code>Unsubscribed = 0;</code>
     */
    const Unsubscribed = 0;
    /**
     * Generated from protobuf enum <code>AccessDenied = 1;</code>
     */
    const AccessDenied = 1;
    /**
     * Generated from protobuf enum <code>NotFound = 2;</code>
     */
    const NotFound = 2;
    /**
     * Generated from protobuf enum <code>PersistentSubscriptionDeleted = 3;</code>
     */
    const PersistentSubscriptionDeleted = 3;
    /**
     * Generated from protobuf enum <code>SubscriberMaxCountReached = 4;</code>
     */
    const SubscriberMaxCountReached = 4;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SubscriptionDropReason::class, \Rxnet\EventStore\Data\SubscriptionDropped_SubscriptionDropReason::class);

