<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data\ReadEventCompleted;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.ReadEventCompleted.ReadEventResult</code>
 */
class ReadEventResult
{
    /**
     * Generated from protobuf enum <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * Generated from protobuf enum <code>NotFound = 1;</code>
     */
    const NotFound = 1;
    /**
     * Generated from protobuf enum <code>NoStream = 2;</code>
     */
    const NoStream = 2;
    /**
     * Generated from protobuf enum <code>StreamDeleted = 3;</code>
     */
    const StreamDeleted = 3;
    /**
     * Generated from protobuf enum <code>Error = 4;</code>
     */
    const Error = 4;
    /**
     * Generated from protobuf enum <code>AccessDenied = 5;</code>
     */
    const AccessDenied = 5;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ReadEventResult::class, \Rxnet\EventStore\Data\ReadEventCompleted_ReadEventResult::class);

