<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.ConnectToPersistentSubscription</code>
 */
class ConnectToPersistentSubscription extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string subscription_id = 1;</code>
     */
    private $subscription_id = '';
    /**
     * <code>string event_stream_id = 2;</code>
     */
    private $event_stream_id = '';
    /**
     * <code>int32 allowed_in_flight_messages = 3;</code>
     */
    private $allowed_in_flight_messages = 0;

    public function __construct() {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * <code>string subscription_id = 1;</code>
     */
    public function getSubscriptionId()
    {
        return $this->subscription_id;
    }

    /**
     * <code>string subscription_id = 1;</code>
     */
    public function setSubscriptionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->subscription_id = $var;
    }

    /**
     * <code>string event_stream_id = 2;</code>
     */
    public function getEventStreamId()
    {
        return $this->event_stream_id;
    }

    /**
     * <code>string event_stream_id = 2;</code>
     */
    public function setEventStreamId($var)
    {
        GPBUtil::checkString($var, True);
        $this->event_stream_id = $var;
    }

    /**
     * <code>int32 allowed_in_flight_messages = 3;</code>
     */
    public function getAllowedInFlightMessages()
    {
        return $this->allowed_in_flight_messages;
    }

    /**
     * <code>int32 allowed_in_flight_messages = 3;</code>
     */
    public function setAllowedInFlightMessages($var)
    {
        GPBUtil::checkInt32($var);
        $this->allowed_in_flight_messages = $var;
    }

}

