<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

/**
 * Protobuf enum <code>Rxnet.EventStore.Data.CreatePersistentSubscriptionCompleted.CreatePersistentSubscriptionResult</code>
 */
class CreatePersistentSubscriptionCompleted_CreatePersistentSubscriptionResult
{
    /**
     * <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * <code>AlreadyExists = 1;</code>
     */
    const AlreadyExists = 1;
    /**
     * <code>Fail = 2;</code>
     */
    const Fail = 2;
    /**
     * <code>AccessDenied = 3;</code>
     */
    const AccessDenied = 3;
}

