<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

if (false) {
    /**
     * This class is deprecated. Use Rxnet\EventStore\Data\CreatePersistentSubscriptionCompleted\CreatePersistentSubscriptionResult instead.
     * @deprecated
     */
    class CreatePersistentSubscriptionCompleted_CreatePersistentSubscriptionResult {}
}
class_exists(CreatePersistentSubscriptionCompleted\CreatePersistentSubscriptionResult::class);
@trigger_error('Rxnet\EventStore\Data\CreatePersistentSubscriptionCompleted_CreatePersistentSubscriptionResult is deprecated and will be removed in the next major release. Use Rxnet\EventStore\Data\CreatePersistentSubscriptionCompleted\CreatePersistentSubscriptionResult instead', E_USER_DEPRECATED);

