<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

if (false) {
    /**
     * This class is deprecated. Use Rxnet\EventStore\Data\DeletePersistentSubscriptionCompleted\DeletePersistentSubscriptionResult instead.
     * @deprecated
     */
    class DeletePersistentSubscriptionCompleted_DeletePersistentSubscriptionResult {}
}
class_exists(DeletePersistentSubscriptionCompleted\DeletePersistentSubscriptionResult::class);
@trigger_error('Rxnet\EventStore\Data\DeletePersistentSubscriptionCompleted_DeletePersistentSubscriptionResult is deprecated and will be removed in the next major release. Use Rxnet\EventStore\Data\DeletePersistentSubscriptionCompleted\DeletePersistentSubscriptionResult instead', E_USER_DEPRECATED);

