<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

if (false) {
    /**
     * This class is deprecated. Use Rxnet\EventStore\Data\NotHandled\MasterInfo instead.
     * @deprecated
     */
    class NotHandled_MasterInfo {}
}
class_exists(NotHandled\MasterInfo::class);
@trigger_error('Rxnet\EventStore\Data\NotHandled_MasterInfo is deprecated and will be removed in the next major release. Use Rxnet\EventStore\Data\NotHandled\MasterInfo instead', E_USER_DEPRECATED);

