<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.NotHandled.MasterInfo</code>
 */
class NotHandled_MasterInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string external_tcp_address = 1;</code>
     */
    private $external_tcp_address = '';
    /**
     * <code>int32 external_tcp_port = 2;</code>
     */
    private $external_tcp_port = 0;
    /**
     * <code>string external_http_address = 3;</code>
     */
    private $external_http_address = '';
    /**
     * <code>int32 external_http_port = 4;</code>
     */
    private $external_http_port = 0;
    /**
     * <code>string external_secure_tcp_address = 5;</code>
     */
    private $external_secure_tcp_address = '';
    /**
     * <code>int32 external_secure_tcp_port = 6;</code>
     */
    private $external_secure_tcp_port = 0;

    public function __construct() {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * <code>string external_tcp_address = 1;</code>
     */
    public function getExternalTcpAddress()
    {
        return $this->external_tcp_address;
    }

    /**
     * <code>string external_tcp_address = 1;</code>
     */
    public function setExternalTcpAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->external_tcp_address = $var;
    }

    /**
     * <code>int32 external_tcp_port = 2;</code>
     */
    public function getExternalTcpPort()
    {
        return $this->external_tcp_port;
    }

    /**
     * <code>int32 external_tcp_port = 2;</code>
     */
    public function setExternalTcpPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->external_tcp_port = $var;
    }

    /**
     * <code>string external_http_address = 3;</code>
     */
    public function getExternalHttpAddress()
    {
        return $this->external_http_address;
    }

    /**
     * <code>string external_http_address = 3;</code>
     */
    public function setExternalHttpAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->external_http_address = $var;
    }

    /**
     * <code>int32 external_http_port = 4;</code>
     */
    public function getExternalHttpPort()
    {
        return $this->external_http_port;
    }

    /**
     * <code>int32 external_http_port = 4;</code>
     */
    public function setExternalHttpPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->external_http_port = $var;
    }

    /**
     * <code>string external_secure_tcp_address = 5;</code>
     */
    public function getExternalSecureTcpAddress()
    {
        return $this->external_secure_tcp_address;
    }

    /**
     * <code>string external_secure_tcp_address = 5;</code>
     */
    public function setExternalSecureTcpAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->external_secure_tcp_address = $var;
    }

    /**
     * <code>int32 external_secure_tcp_port = 6;</code>
     */
    public function getExternalSecureTcpPort()
    {
        return $this->external_secure_tcp_port;
    }

    /**
     * <code>int32 external_secure_tcp_port = 6;</code>
     */
    public function setExternalSecureTcpPort($var)
    {
        GPBUtil::checkInt32($var);
        $this->external_secure_tcp_port = $var;
    }

}

