<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

/**
 * Protobuf enum <code>Rxnet.EventStore.Data.NotHandled.NotHandledReason</code>
 */
class NotHandled_NotHandledReason
{
    /**
     * <code>NotReady = 0;</code>
     */
    const NotReady = 0;
    /**
     * <code>TooBusy = 1;</code>
     */
    const TooBusy = 1;
    /**
     * <code>NotMaster = 2;</code>
     */
    const NotMaster = 2;
}

