<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

if (false) {
    /**
     * This class is deprecated. Use Rxnet\EventStore\Data\NotHandled\NotHandledReason instead.
     * @deprecated
     */
    class NotHandled_NotHandledReason {}
}
class_exists(NotHandled\NotHandledReason::class);
@trigger_error('Rxnet\EventStore\Data\NotHandled_NotHandledReason is deprecated and will be removed in the next major release. Use Rxnet\EventStore\Data\NotHandled\NotHandledReason instead', E_USER_DEPRECATED);

