<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.NotHandled</code>
 */
class NotHandled extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.Rxnet.EventStore.Data.NotHandled.NotHandledReason reason = 1;</code>
     */
    private $reason = 0;
    /**
     * <code>bytes additional_info = 2;</code>
     */
    private $additional_info = '';

    public function __construct() {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * <code>.Rxnet.EventStore.Data.NotHandled.NotHandledReason reason = 1;</code>
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * <code>.Rxnet.EventStore.Data.NotHandled.NotHandledReason reason = 1;</code>
     */
    public function setReason($var)
    {
        GPBUtil::checkEnum($var, \Rxnet\EventStore\Data\NotHandled_NotHandledReason::class);
        $this->reason = $var;
    }

    /**
     * <code>bytes additional_info = 2;</code>
     */
    public function getAdditionalInfo()
    {
        return $this->additional_info;
    }

    /**
     * <code>bytes additional_info = 2;</code>
     */
    public function setAdditionalInfo($var)
    {
        GPBUtil::checkString($var, False);
        $this->additional_info = $var;
    }

}

