<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.PersistentSubscriptionAckEvents</code>
 */
class PersistentSubscriptionAckEvents extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string subscription_id = 1;</code>
     */
    private $subscription_id = '';
    /**
     * <code>repeated bytes processed_event_ids = 2;</code>
     */
    private $processed_event_ids;

    public function __construct() {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * <code>string subscription_id = 1;</code>
     */
    public function getSubscriptionId()
    {
        return $this->subscription_id;
    }

    /**
     * <code>string subscription_id = 1;</code>
     */
    public function setSubscriptionId($var)
    {
        GPBUtil::checkString($var, True);
        $this->subscription_id = $var;
    }

    /**
     * <code>repeated bytes processed_event_ids = 2;</code>
     */
    public function getProcessedEventIds()
    {
        return $this->processed_event_ids;
    }

    /**
     * <code>repeated bytes processed_event_ids = 2;</code>
     */
    public function setProcessedEventIds(&$var)
    {
        GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->processed_event_ids = $var;
    }

}

