<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rxnet.EventStore.Data.PersistentSubscriptionStreamEventAppeared</code>
 */
class PersistentSubscriptionStreamEventAppeared extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Rxnet.EventStore.Data.ResolvedIndexedEvent event = 1;</code>
     */
    private $event = null;
    /**
     * Generated from protobuf field <code>int32 retryCount = 2;</code>
     */
    private $retryCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rxnet\EventStore\Data\ResolvedIndexedEvent $event
     *     @type int $retryCount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Rxnet.EventStore.Data.ResolvedIndexedEvent event = 1;</code>
     * @return \Rxnet\EventStore\Data\ResolvedIndexedEvent
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>.Rxnet.EventStore.Data.ResolvedIndexedEvent event = 1;</code>
     * @param \Rxnet\EventStore\Data\ResolvedIndexedEvent $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkMessage($var, \Rxnet\EventStore\Data\ResolvedIndexedEvent::class);
        $this->event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 retryCount = 2;</code>
     * @return int
     */
    public function getRetryCount()
    {
        return $this->retryCount;
    }

    /**
     * Generated from protobuf field <code>int32 retryCount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setRetryCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->retryCount = $var;

        return $this;
    }

}

