<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

if (false) {
    /**
     * This class is deprecated. Use Rxnet\EventStore\Data\PersistentSubscriptionNakEvents\NakAction instead.
     * @deprecated
     */
    class PersistentSubscriptionNakEvents_NakAction {}
}
class_exists(PersistentSubscriptionNakEvents\NakAction::class);
@trigger_error('Rxnet\EventStore\Data\PersistentSubscriptionNakEvents_NakAction is deprecated and will be removed in the next major release. Use Rxnet\EventStore\Data\PersistentSubscriptionNakEvents\NakAction instead', E_USER_DEPRECATED);

