<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

/**
 * Protobuf enum <code>Rxnet.EventStore.Data.PersistentSubscriptionNakEvents.NakAction</code>
 */
class PersistentSubscriptionNakEvents_NakAction
{
    /**
     * <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * <code>Park = 1;</code>
     */
    const Park = 1;
    /**
     * <code>Retry = 2;</code>
     */
    const Retry = 2;
    /**
     * <code>Skip = 3;</code>
     */
    const Skip = 3;
    /**
     * <code>Stop = 4;</code>
     */
    const Stop = 4;
}

