<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.PersistentSubscriptionStreamEventAppeared</code>
 */
class PersistentSubscriptionStreamEventAppeared extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.Rxnet.EventStore.Data.ResolvedIndexedEvent event = 1;</code>
     */
    private $event = null;

    public function __construct() {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * <code>.Rxnet.EventStore.Data.ResolvedIndexedEvent event = 1;</code>
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * <code>.Rxnet.EventStore.Data.ResolvedIndexedEvent event = 1;</code>
     */
    public function setEvent(&$var)
    {
        GPBUtil::checkMessage($var, \Rxnet\EventStore\Data\ResolvedIndexedEvent::class);
        $this->event = $var;
    }

}

