<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

/**
 * Protobuf enum <code>Rxnet.EventStore.Data.ReadStreamEventsCompleted.ReadStreamResult</code>
 */
class ReadStreamEventsCompleted_ReadStreamResult
{
    /**
     * <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * <code>NoStream = 1;</code>
     */
    const NoStream = 1;
    /**
     * <code>StreamDeleted = 2;</code>
     */
    const StreamDeleted = 2;
    /**
     * <code>NotModified = 3;</code>
     */
    const NotModified = 3;
    /**
     * <code>Error = 4;</code>
     */
    const Error = 4;
    /**
     * <code>AccessDenied = 5;</code>
     */
    const AccessDenied = 5;
}

