<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

/**
 * Protobuf enum <code>Rxnet.EventStore.Data.ReadAllEventsCompleted.ReadAllResult</code>
 */
class ReadAllEventsCompleted_ReadAllResult
{
    /**
     * <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * <code>NotModified = 1;</code>
     */
    const NotModified = 1;
    /**
     * <code>Error = 2;</code>
     */
    const Error = 2;
    /**
     * <code>AccessDenied = 3;</code>
     */
    const AccessDenied = 3;
}

