<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.ReadStreamEventsCompleted</code>
 */
class ReadStreamEventsCompleted extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>repeated .Rxnet.EventStore.Data.ResolvedIndexedEvent events = 1;</code>
     */
    private $events;
    /**
     * <code>.Rxnet.EventStore.Data.ReadStreamEventsCompleted.ReadStreamResult result = 2;</code>
     */
    private $result = 0;
    /**
     * <code>int64 next_event_number = 3;</code>
     */
    private $next_event_number = 0;
    /**
     * <code>int64 last_event_number = 4;</code>
     */
    private $last_event_number = 0;
    /**
     * <code>bool is_end_of_stream = 5;</code>
     */
    private $is_end_of_stream = false;
    /**
     * <code>int64 last_commit_position = 6;</code>
     */
    private $last_commit_position = 0;
    /**
     * <code>string error = 7;</code>
     */
    private $error = '';

    public function __construct() {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * <code>repeated .Rxnet.EventStore.Data.ResolvedIndexedEvent events = 1;</code>
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * <code>repeated .Rxnet.EventStore.Data.ResolvedIndexedEvent events = 1;</code>
     */
    public function setEvents(&$var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rxnet\EventStore\Data\ResolvedIndexedEvent::class);
        $this->events = $arr;
    }

    /**
     * <code>.Rxnet.EventStore.Data.ReadStreamEventsCompleted.ReadStreamResult result = 2;</code>
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * <code>.Rxnet.EventStore.Data.ReadStreamEventsCompleted.ReadStreamResult result = 2;</code>
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Rxnet\EventStore\Data\ReadStreamEventsCompleted_ReadStreamResult::class);
        $this->result = $var;
    }

    /**
     * <code>int64 next_event_number = 3;</code>
     */
    public function getNextEventNumber()
    {
        return $this->next_event_number;
    }

    /**
     * <code>int64 next_event_number = 3;</code>
     */
    public function setNextEventNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->next_event_number = $var;
    }

    /**
     * <code>int64 last_event_number = 4;</code>
     */
    public function getLastEventNumber()
    {
        return $this->last_event_number;
    }

    /**
     * <code>int64 last_event_number = 4;</code>
     */
    public function setLastEventNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_event_number = $var;
    }

    /**
     * <code>bool is_end_of_stream = 5;</code>
     */
    public function getIsEndOfStream()
    {
        return $this->is_end_of_stream;
    }

    /**
     * <code>bool is_end_of_stream = 5;</code>
     */
    public function setIsEndOfStream($var)
    {
        GPBUtil::checkBool($var);
        $this->is_end_of_stream = $var;
    }

    /**
     * <code>int64 last_commit_position = 6;</code>
     */
    public function getLastCommitPosition()
    {
        return $this->last_commit_position;
    }

    /**
     * <code>int64 last_commit_position = 6;</code>
     */
    public function setLastCommitPosition($var)
    {
        GPBUtil::checkInt64($var);
        $this->last_commit_position = $var;
    }

    /**
     * <code>string error = 7;</code>
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * <code>string error = 7;</code>
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;
    }

}

