<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

if (false) {
    /**
     * This class is deprecated. Use Rxnet\EventStore\Data\ReadEventCompleted\ReadEventResult instead.
     * @deprecated
     */
    class ReadEventCompleted_ReadEventResult {}
}
class_exists(ReadEventCompleted\ReadEventResult::class);
@trigger_error('Rxnet\EventStore\Data\ReadEventCompleted_ReadEventResult is deprecated and will be removed in the next major release. Use Rxnet\EventStore\Data\ReadEventCompleted\ReadEventResult instead', E_USER_DEPRECATED);

