<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.ReadEvent</code>
 */
class ReadEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string event_stream_id = 1;</code>
     */
    private $event_stream_id = '';
    /**
     * <code>int64 event_number = 2;</code>
     */
    private $event_number = 0;
    /**
     * <code>bool resolve_link_tos = 3;</code>
     */
    private $resolve_link_tos = false;
    /**
     * <code>bool require_master = 4;</code>
     */
    private $require_master = false;

    public function __construct() {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * <code>string event_stream_id = 1;</code>
     */
    public function getEventStreamId()
    {
        return $this->event_stream_id;
    }

    /**
     * <code>string event_stream_id = 1;</code>
     */
    public function setEventStreamId($var)
    {
        GPBUtil::checkString($var, True);
        $this->event_stream_id = $var;
    }

    /**
     * <code>int64 event_number = 2;</code>
     */
    public function getEventNumber()
    {
        return $this->event_number;
    }

    /**
     * <code>int64 event_number = 2;</code>
     */
    public function setEventNumber($var)
    {
        GPBUtil::checkInt64($var);
        $this->event_number = $var;
    }

    /**
     * <code>bool resolve_link_tos = 3;</code>
     */
    public function getResolveLinkTos()
    {
        return $this->resolve_link_tos;
    }

    /**
     * <code>bool resolve_link_tos = 3;</code>
     */
    public function setResolveLinkTos($var)
    {
        GPBUtil::checkBool($var);
        $this->resolve_link_tos = $var;
    }

    /**
     * <code>bool require_master = 4;</code>
     */
    public function getRequireMaster()
    {
        return $this->require_master;
    }

    /**
     * <code>bool require_master = 4;</code>
     */
    public function setRequireMaster($var)
    {
        GPBUtil::checkBool($var);
        $this->require_master = $var;
    }

}

