<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

if (false) {
    /**
     * This class is deprecated. Use Rxnet\EventStore\Data\ReadAllEventsCompleted\ReadAllResult instead.
     * @deprecated
     */
    class ReadAllEventsCompleted_ReadAllResult {}
}
class_exists(ReadAllEventsCompleted\ReadAllResult::class);
@trigger_error('Rxnet\EventStore\Data\ReadAllEventsCompleted_ReadAllResult is deprecated and will be removed in the next major release. Use Rxnet\EventStore\Data\ReadAllEventsCompleted\ReadAllResult instead', E_USER_DEPRECATED);

