<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.ReadEventCompleted</code>
 */
class ReadEventCompleted extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.Rxnet.EventStore.Data.ReadEventCompleted.ReadEventResult result = 1;</code>
     */
    private $result = 0;
    /**
     * <code>.Rxnet.EventStore.Data.ResolvedIndexedEvent event = 2;</code>
     */
    private $event = null;
    /**
     * <code>string error = 3;</code>
     */
    private $error = '';

    public function __construct() {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * <code>.Rxnet.EventStore.Data.ReadEventCompleted.ReadEventResult result = 1;</code>
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * <code>.Rxnet.EventStore.Data.ReadEventCompleted.ReadEventResult result = 1;</code>
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Rxnet\EventStore\Data\ReadEventCompleted_ReadEventResult::class);
        $this->result = $var;
    }

    /**
     * <code>.Rxnet.EventStore.Data.ResolvedIndexedEvent event = 2;</code>
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * <code>.Rxnet.EventStore.Data.ResolvedIndexedEvent event = 2;</code>
     */
    public function setEvent(&$var)
    {
        GPBUtil::checkMessage($var, \Rxnet\EventStore\Data\ResolvedIndexedEvent::class);
        $this->event = $var;
    }

    /**
     * <code>string error = 3;</code>
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * <code>string error = 3;</code>
     */
    public function setError($var)
    {
        GPBUtil::checkString($var, True);
        $this->error = $var;
    }

}

