<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

if (false) {
    /**
     * This class is deprecated. Use Rxnet\EventStore\Data\ReadStreamEventsCompleted\ReadStreamResult instead.
     * @deprecated
     */
    class ReadStreamEventsCompleted_ReadStreamResult {}
}
class_exists(ReadStreamEventsCompleted\ReadStreamResult::class);
@trigger_error('Rxnet\EventStore\Data\ReadStreamEventsCompleted_ReadStreamResult is deprecated and will be removed in the next major release. Use Rxnet\EventStore\Data\ReadStreamEventsCompleted\ReadStreamResult instead', E_USER_DEPRECATED);

