<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rxnet.EventStore.Data.ResolvedIndexedEvent</code>
 */
class ResolvedIndexedEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Rxnet.EventStore.Data.EventRecord event = 1;</code>
     */
    private $event = null;
    /**
     * Generated from protobuf field <code>.Rxnet.EventStore.Data.EventRecord link = 2;</code>
     */
    private $link = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rxnet\EventStore\Data\EventRecord $event
     *     @type \Rxnet\EventStore\Data\EventRecord $link
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Rxnet.EventStore.Data.EventRecord event = 1;</code>
     * @return \Rxnet\EventStore\Data\EventRecord
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>.Rxnet.EventStore.Data.EventRecord event = 1;</code>
     * @param \Rxnet\EventStore\Data\EventRecord $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkMessage($var, \Rxnet\EventStore\Data\EventRecord::class);
        $this->event = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Rxnet.EventStore.Data.EventRecord link = 2;</code>
     * @return \Rxnet\EventStore\Data\EventRecord
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * Generated from protobuf field <code>.Rxnet.EventStore.Data.EventRecord link = 2;</code>
     * @param \Rxnet\EventStore\Data\EventRecord $var
     * @return $this
     */
    public function setLink($var)
    {
        GPBUtil::checkMessage($var, \Rxnet\EventStore\Data\EventRecord::class);
        $this->link = $var;

        return $this;
    }

}

