<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.ResolvedIndexedEvent</code>
 */
class ResolvedIndexedEvent extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.Rxnet.EventStore.Data.EventRecord event = 1;</code>
     */
    private $event = null;
    /**
     * <code>.Rxnet.EventStore.Data.EventRecord link = 2;</code>
     */
    private $link = null;

    public function __construct() {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * <code>.Rxnet.EventStore.Data.EventRecord event = 1;</code>
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * <code>.Rxnet.EventStore.Data.EventRecord event = 1;</code>
     */
    public function setEvent(&$var)
    {
        GPBUtil::checkMessage($var, \Rxnet\EventStore\Data\EventRecord::class);
        $this->event = $var;
    }

    /**
     * <code>.Rxnet.EventStore.Data.EventRecord link = 2;</code>
     */
    public function getLink()
    {
        return $this->link;
    }

    /**
     * <code>.Rxnet.EventStore.Data.EventRecord link = 2;</code>
     */
    public function setLink(&$var)
    {
        GPBUtil::checkMessage($var, \Rxnet\EventStore\Data\EventRecord::class);
        $this->link = $var;
    }

}

