<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

if (false) {
    /**
     * This class is deprecated. Use Rxnet\EventStore\Data\ScavengeDatabaseCompleted\ScavengeResult instead.
     * @deprecated
     */
    class ScavengeDatabaseCompleted_ScavengeResult {}
}
class_exists(ScavengeDatabaseCompleted\ScavengeResult::class);
@trigger_error('Rxnet\EventStore\Data\ScavengeDatabaseCompleted_ScavengeResult is deprecated and will be removed in the next major release. Use Rxnet\EventStore\Data\ScavengeDatabaseCompleted\ScavengeResult instead', E_USER_DEPRECATED);

