<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

/**
 * Protobuf enum <code>Rxnet.EventStore.Data.ScavengeDatabaseCompleted.ScavengeResult</code>
 */
class ScavengeDatabaseCompleted_ScavengeResult
{
    /**
     * <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * <code>InProgress = 1;</code>
     */
    const InProgress = 1;
    /**
     * <code>Failed = 2;</code>
     */
    const Failed = 2;
}

