<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rxnet.EventStore.Data.StreamEventAppeared</code>
 */
class StreamEventAppeared extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Rxnet.EventStore.Data.ResolvedEvent event = 1;</code>
     */
    private $event = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rxnet\EventStore\Data\ResolvedEvent $event
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Rxnet.EventStore.Data.ResolvedEvent event = 1;</code>
     * @return \Rxnet\EventStore\Data\ResolvedEvent
     */
    public function getEvent()
    {
        return $this->event;
    }

    /**
     * Generated from protobuf field <code>.Rxnet.EventStore.Data.ResolvedEvent event = 1;</code>
     * @param \Rxnet\EventStore\Data\ResolvedEvent $var
     * @return $this
     */
    public function setEvent($var)
    {
        GPBUtil::checkMessage($var, \Rxnet\EventStore\Data\ResolvedEvent::class);
        $this->event = $var;

        return $this;
    }

}

