<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

if (false) {
    /**
     * This class is deprecated. Use Rxnet\EventStore\Data\SubscriptionDropped\SubscriptionDropReason instead.
     * @deprecated
     */
    class SubscriptionDropped_SubscriptionDropReason {}
}
class_exists(SubscriptionDropped\SubscriptionDropReason::class);
@trigger_error('Rxnet\EventStore\Data\SubscriptionDropped_SubscriptionDropReason is deprecated and will be removed in the next major release. Use Rxnet\EventStore\Data\SubscriptionDropped\SubscriptionDropReason instead', E_USER_DEPRECATED);

