<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

/**
 * Protobuf enum <code>Rxnet.EventStore.Data.SubscriptionDropped.SubscriptionDropReason</code>
 */
class SubscriptionDropped_SubscriptionDropReason
{
    /**
     * <code>Unsubscribed = 0;</code>
     */
    const Unsubscribed = 0;
    /**
     * <code>AccessDenied = 1;</code>
     */
    const AccessDenied = 1;
    /**
     * <code>NotFound = 2;</code>
     */
    const NotFound = 2;
    /**
     * <code>PersistentSubscriptionDeleted = 3;</code>
     */
    const PersistentSubscriptionDeleted = 3;
    /**
     * <code>SubscriberMaxCountReached = 4;</code>
     */
    const SubscriberMaxCountReached = 4;
}

