<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.SubscriptionDropped</code>
 */
class SubscriptionDropped extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.Rxnet.EventStore.Data.SubscriptionDropped.SubscriptionDropReason reason = 1;</code>
     */
    private $reason = 0;

    public function __construct() {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * <code>.Rxnet.EventStore.Data.SubscriptionDropped.SubscriptionDropReason reason = 1;</code>
     */
    public function getReason()
    {
        return $this->reason;
    }

    /**
     * <code>.Rxnet.EventStore.Data.SubscriptionDropped.SubscriptionDropReason reason = 1;</code>
     */
    public function setReason($var)
    {
        GPBUtil::checkEnum($var, \Rxnet\EventStore\Data\SubscriptionDropped_SubscriptionDropReason::class);
        $this->reason = $var;
    }

}

