<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.TransactionWriteCompleted</code>
 */
class TransactionWriteCompleted extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 transaction_id = 1;</code>
     */
    private $transaction_id = 0;
    /**
     * <code>.Rxnet.EventStore.Data.OperationResult result = 2;</code>
     */
    private $result = 0;
    /**
     * <code>string message = 3;</code>
     */
    private $message = '';

    public function __construct() {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 transaction_id = 1;</code>
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * <code>int64 transaction_id = 1;</code>
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->transaction_id = $var;
    }

    /**
     * <code>.Rxnet.EventStore.Data.OperationResult result = 2;</code>
     */
    public function getResult()
    {
        return $this->result;
    }

    /**
     * <code>.Rxnet.EventStore.Data.OperationResult result = 2;</code>
     */
    public function setResult($var)
    {
        GPBUtil::checkEnum($var, \Rxnet\EventStore\Data\OperationResult::class);
        $this->result = $var;
    }

    /**
     * <code>string message = 3;</code>
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * <code>string message = 3;</code>
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;
    }

}

