<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.TransactionCommit</code>
 */
class TransactionCommit extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int64 transaction_id = 1;</code>
     */
    private $transaction_id = 0;
    /**
     * <code>bool require_master = 2;</code>
     */
    private $require_master = false;

    public function __construct() {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct();
    }

    /**
     * <code>int64 transaction_id = 1;</code>
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * <code>int64 transaction_id = 1;</code>
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->transaction_id = $var;
    }

    /**
     * <code>bool require_master = 2;</code>
     */
    public function getRequireMaster()
    {
        return $this->require_master;
    }

    /**
     * <code>bool require_master = 2;</code>
     */
    public function setRequireMaster($var)
    {
        GPBUtil::checkBool($var);
        $this->require_master = $var;
    }

}

