<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Rxnet.EventStore.Data.TransactionWrite</code>
 */
class TransactionWrite extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int64 transaction_id = 1;</code>
     */
    private $transaction_id = 0;
    /**
     * Generated from protobuf field <code>repeated .Rxnet.EventStore.Data.NewEvent events = 2;</code>
     */
    private $events;
    /**
     * Generated from protobuf field <code>bool require_master = 3;</code>
     */
    private $require_master = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $transaction_id
     *     @type \Rxnet\EventStore\Data\NewEvent[]|\Google\Protobuf\Internal\RepeatedField $events
     *     @type bool $require_master
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ClientMessageDtos::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int64 transaction_id = 1;</code>
     * @return int|string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>int64 transaction_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->transaction_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Rxnet.EventStore.Data.NewEvent events = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .Rxnet.EventStore.Data.NewEvent events = 2;</code>
     * @param \Rxnet\EventStore\Data\NewEvent[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rxnet\EventStore\Data\NewEvent::class);
        $this->events = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool require_master = 3;</code>
     * @return bool
     */
    public function getRequireMaster()
    {
        return $this->require_master;
    }

    /**
     * Generated from protobuf field <code>bool require_master = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setRequireMaster($var)
    {
        GPBUtil::checkBool($var);
        $this->require_master = $var;

        return $this;
    }

}

