<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data;

if (false) {
    /**
     * This class is deprecated. Use Rxnet\EventStore\Data\UpdatePersistentSubscriptionCompleted\UpdatePersistentSubscriptionResult instead.
     * @deprecated
     */
    class UpdatePersistentSubscriptionCompleted_UpdatePersistentSubscriptionResult {}
}
class_exists(UpdatePersistentSubscriptionCompleted\UpdatePersistentSubscriptionResult::class);
@trigger_error('Rxnet\EventStore\Data\UpdatePersistentSubscriptionCompleted_UpdatePersistentSubscriptionResult is deprecated and will be removed in the next major release. Use Rxnet\EventStore\Data\UpdatePersistentSubscriptionCompleted\UpdatePersistentSubscriptionResult instead', E_USER_DEPRECATED);

