<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientMessageDtos.proto

namespace Rxnet\EventStore\Data\ScavengeDatabaseCompleted;

/**
 * Protobuf type <code>Rxnet.EventStore.Data.ScavengeDatabaseCompleted.ScavengeResult</code>
 */
class ScavengeResult
{
    /**
     * Generated from protobuf enum <code>Success = 0;</code>
     */
    const Success = 0;
    /**
     * Generated from protobuf enum <code>InProgress = 1;</code>
     */
    const InProgress = 1;
    /**
     * Generated from protobuf enum <code>Failed = 2;</code>
     */
    const Failed = 2;
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(ScavengeResult::class, \Rxnet\EventStore\Data\ScavengeDatabaseCompleted_ScavengeResult::class);

